function choice = choosedialog

    d = dialog('Position',[300 300 250 150],'Name','Select One');
    uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Select an Operation');
       
    uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 100 25],...
           'String',{'A*v';'(v^T)*A';'(v^T)*A*v'},...
           'Callback',@popup_callback);
       
    uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Close',...
           'Callback','delete(gcf)');
       
    choice = 'A*v';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
    function popup_callback(popup,~)
        idx = get(popup,'Value');
        popup_items = get(popup,'String');
        choice = char(popup_items(idx,:));
    end
end